<a href="https://colab.research.google.com/github/julianrojas19/julianrojas19.github.io/blob/main/PROYECTO4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install wooldridge
import wooldridge as wd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
from collections import Counter 
from sklearn.linear_model import LinearRegression
import statistics as st

In [ ]:
crime=wd.data("crime1")

In [ ]:
crime

narr86  nfarr86  nparr86  pcnv     avgsen    tottime  ptime86  qemp86  \
0          0        0        0  0.38  17.600000  35.200001       12     0.0   
1          2        2        0  0.44   0.000000   0.000000        0     1.0   
2          1        1        0  0.33  22.799999  22.799999        0     0.0   
3          2        2        1  0.25   0.000000   0.000000        5     2.0   
4          1        1        0  0.00   0.000000   0.000000        0     2.0   
...      ...      ...      ...   ...        ...        ...      ...     ...   
2720       1        1        0  0.00   0.000000   0.000000        0     0.0   
2721       0        0        0  0.00   0.000000   0.000000        0     3.0   
2722       0        0        0  0.00   0.000000   0.000000        0     1.0   
2723       1        1        0  0.00   0.000000   0.000000        0     0.0   
2724       0        0        0  0.00   0.000000   0.000000        0     4.0   

           inc86  durat  black  hispan  born60  pcnvsq  pt86sq       inc86sq  
0       0.000000    0.0      0       0       1  0.1444     144      0.000000  
1       0.800000    0.0      0       1       0  0.1936       0      0.640000  
2       0.000000   11.0      1       0       1  0.1089       0      0.000000  
3       8.800000    0.0      0       1       1  0.0625      25     77.440002  
4       8.100000    1.0      0       0       0  0.0000       0     65.610008  
...          ...    ...    ...     ...     ...     ...     ...           ...  
2720    0.000000    3.0      0       0       0  0.0000       0      0.000000  
2721   11.500000    1.0      0       1       1  0.0000       0    132.250000  
2722    1.900000    1.0      0       0       0  0.0000       0      3.610000  
2723    0.000000   19.0      1       0       0  0.0000       0      0.000000  
2724  191.300003    0.0      0       0       1  0.0000       0  36595.691406  

[2725 rows x 16 columns]

In [ ]:
from operator import index
class info_econo:
  def __init__(self,Y,X):
    self.x=X
    self.dim=(2725,1)
    self.MU=np.ones(self.dim)
    self.XZ=np.concatenate((self.MU,self.x),1)
    self.y=Y.to_numpy().reshape(-1,1)
    self.XT=self.XZ.T
    self.X1=self.XT@self.XZ
    self.XI=np.linalg.inv(self.X1)
    self.XM=self.XT@self.y
  def coeficiente(self):
    return (self.XI@self.XM).reshape(-1,1)
  def error(self):
    self.b=self.coeficiente().reshape(-1,1)
    self.n=len(self.y)
    self.k=(self.x).shape[1]
    self.OP=(self.y-self.XZ @ self.coeficiente())
    self.num=self.OP.T @ self.OP
    self.den=self.n-self.k-1
    self.var=self.num/self.den
    self.var[0][0]
    self.ME=self.var * self.XI
    return np.sqrt(np.diag(self.ME)).reshape(-1,1)
  def T_stat(self):
    return (self.coeficiente()/self.error()).reshape(-1,1)
  def int_conf(self):
    self.pos=(self.coeficiente()+1.96*self.error())
    self.neg=(self.coeficiente()-1.96*self.error())
    self.INT=list(zip(self.neg,self.pos))
    return self.INT

In [ ]:
crime=wd.data("crime1")

In [ ]:
datos1=info_econo(crime["narr86"],crime[["pcnv","avgsen","tottime","inc86"]])

In [ ]:
datos1.coeficiente()

array([[ 0.59387489],
       [-0.16243696],
       [-0.00618803],
       [ 0.00771062],
       [-0.00243615]])

In [ ]:
datos1.error()

array([[0.02585771],
       [0.04081609],
       [0.01238073],
       [0.009432  ],
       [0.00024321]])

In [ ]:
datos1.T_stat()

array([[ 22.9670375 ],
       [ -3.97972866],
       [ -0.49981111],
       [  0.81749603],
       [-10.01685265]])

In [ ]:
datos1.int_conf()

[(array([0.54319379]), array([0.64455599])),
 (array([-0.24243649]), array([-0.08243742])),
 (array([-0.03045426]), array([0.01807821])),
 (array([-0.0107761]), array([0.02619734])),
 (array([-0.00291283]), array([-0.00195947]))]

A partir de los resultados obtenidos en los coeficientes, podemos determinar que por cada unidad que aumentemos en la proporcion de condenas anteriores, disminuira 0,16 la cantidad de veces arrestado. Por cada mes de duración promedio de las condenas anteriores, la cantidad de veces arrestado disminuira en 0,006. Por cada unidad de tiempo que aumente en la carcel (18 meses=1 unidad), la cantidad de veces arrestado aumentara en 0,007. Finalmente por cada unidad de ingreso que aumente la persona, disminuira en 0,002 la probabilidad de que vuelva a la carcel.

El error estandar nos muestra la diferencia la diferencia entre la regresión y los datos reales, es decir que en este caso el sesgo que puede presentar cada variable es muy baja.

Con respecto al estadistico T se puede argumentar que debido a que los valores absolutos son mayores que el valor critico se pueden rechazar la hipotesis nula, que en este caso es 0,05.

Finalmente con los intervalos de confianza podemos estar 95% seguros de el valor real que presenta cada variable esta dentro de este rango obtenido.

In [ ]:
crime=wd.data("crime1")

In [ ]:
datos1=info_econo(crime["narr86"],crime[["pcnv","avgsen","tottime","inc86", "pcnvsq", "inc86sq"]])

In [ ]:
datos1.coeficiente()

array([[ 5.77523688e-01],
       [ 6.22634460e-01],
       [-6.92546885e-03],
       [ 4.48874198e-03],
       [-4.08083748e-03],
       [-8.26588291e-01],
       [ 8.56614968e-06]])

In [ ]:
datos1.error()

array([[2.99333383e-02],
       [1.54837099e-01],
       [1.22801963e-02],
       [9.36604874e-03],
       [5.29688653e-04],
       [1.56660748e-01],
       [2.13246317e-06]])

In [ ]:
datos1.T_stat()

array([[19.29366122],
       [ 4.02122271],
       [-0.56395425],
       [ 0.47925674],
       [-7.70421918],
       [-5.27629479],
       [ 4.01702116]])

In [ ]:
datos1.int_conf()

[(array([0.51885434]), array([0.63619303])),
 (array([0.31915375]), array([0.92611517])),
 (array([-0.03099465]), array([0.01714372])),
 (array([-0.01386871]), array([0.0228462])),
 (array([-0.00511903]), array([-0.00304265])),
 (array([-1.13364336]), array([-0.51953322])),
 (array([4.38652187e-06]), array([1.27457775e-05]))]